[package]
name = "tcpts"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "tcpts"
path = "./src/main.rs"

[dependencies]
structopt = { version = "0.3.26", default-features = false }
system_shutdown = "3.0.0"